version: "3.8"

services:
  db:
    image: ankane/pgvector
    container_name: resume_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_matcher
    ports:
      - "5432:5432"